# Generated by Django 5.2.12 on 2026-03-26 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_preferred_supplier_product_reorder_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='supplier',
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product__name', 'warehouse__name']},
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preferred_supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='code',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SupplierInvoice',
        ),
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
