# Generated by Django 5.2.12 on 2026-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('closed_shifts', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('critical_anomaly_count', models.PositiveIntegerField(default=0)),
                ('high_anomaly_count', models.PositiveIntegerField(default=0)),
                ('medium_anomaly_count', models.PositiveIntegerField(default=0)),
                ('low_anomaly_count', models.PositiveIntegerField(default=0)),
                ('open_case_count', models.PositiveIntegerField(default=0)),
                ('breached_case_count', models.PositiveIntegerField(default=0)),
                ('escalated_case_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
