# Generated by Django 5.2.12 on 2026-06-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('base_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_balanced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_tenders', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SplitTenderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='multicurrency.splittender')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=120)),
                ('locked_for_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='multicurrency.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='multicurrency.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
