# Generated by Django 5.2.12 on 2026-03-26 22:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0007_remove_supplierpayment_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finance_payments', to='inventory.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_invoices', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
