# Generated by Django 5.2.12 on 2026-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_supplierpayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tax_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('zero_rated', 'Zero Rated'), ('exempt', 'Exempt')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
