# Generated by Django 5.2.12 on 2026-06-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_alter_saleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('zimra_fdms', 'ZIMRA FDMS Direct'), ('middleware', 'Fiscal Middleware'), ('synvas', 'Synvas Fiscbyte'), ('other', 'Other')], default='middleware', max_length=40)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('branch_code', models.CharField(blank=True, max_length=40)),
                ('api_base_url', models.URLField(blank=True)),
                ('api_key_label', models.CharField(blank=True, help_text='Store real keys in environment variables, not here.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=120, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buyer_name', models.CharField(blank=True, max_length=160)),
                ('buyer_tax_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('fiscal_day_number', models.CharField(blank=True, max_length=80)),
                ('fiscal_receipt_number', models.CharField(blank=True, max_length=120)),
                ('fiscal_signature', models.TextField(blank=True)),
                ('fiscal_qr_data', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_invoices', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='fiscalisation.fiscalinvoice')),
            ],
        ),
    ]
