from decimal import Decimal
from io import BytesIO
import csv

from django.db.models import Sum, Count
from django.http import FileResponse, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.accounts.permissions import IsFinance
from apps.accounts.utils import create_audit_log
from .models import SupplierInvoice, SupplierPayment


def money(value):
    if value is None:
        return "0.00"
    return str(value)


def decimal_value(value):
    return Decimal(str(value or 0))


def draw_header(pdf, title, subtitle=""):
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(20 * mm, 280 * mm, "HUTE")
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(20 * mm, 272 * mm, title)

    if subtitle:
        pdf.setFont("Helvetica", 10)
        pdf.drawString(20 * mm, 266 * mm, subtitle)

    pdf.line(20 * mm, 262 * mm, 190 * mm, 262 * mm)


def draw_footer(pdf):
    pdf.setFont("Helvetica", 9)
    pdf.drawString(20 * mm, 12 * mm, "Generated by HUTE ERP")


def serialize_payment(payment):
    invoice = getattr(payment, "invoice", None)
    supplier = getattr(payment, "supplier", None)

    return {
        "id": payment.id,
        "payment_number": getattr(payment, "payment_number", ""),
        "reference": getattr(payment, "reference", "") or getattr(payment, "payment_number", ""),
        "invoice": getattr(payment, "invoice_id", None),
        "invoice_number": getattr(invoice, "invoice_number", "") if invoice else "",
        "supplier": getattr(payment, "supplier_id", None),
        "supplier_name": getattr(supplier, "name", "") if supplier else "",
        "amount": money(getattr(payment, "amount", 0)),
        "payment_method": getattr(payment, "payment_method", ""),
        "payment_date": getattr(payment, "payment_date", None),
        "notes": getattr(payment, "notes", ""),
        "created_at": getattr(payment, "created_at", None),
    }


def serialize_invoice(invoice):
    purchase_order = getattr(invoice, "purchase_order", None)
    supplier = getattr(invoice, "supplier", None)

    payments = [
        serialize_payment(payment)
        for payment in SupplierPayment.objects.filter(invoice=invoice)
        .select_related("invoice", "supplier")
        .order_by("-payment_date", "-created_at")
    ]

    subtotal_amount = decimal_value(getattr(invoice, "subtotal_amount", 0))
    tax_amount = decimal_value(getattr(invoice, "tax_amount", 0))
    total_amount = decimal_value(getattr(invoice, "total_amount", 0))
    amount_paid = decimal_value(getattr(invoice, "amount_paid", 0))
    balance_due = decimal_value(getattr(invoice, "balance_due", total_amount - amount_paid))

    due_date = getattr(invoice, "due_date", None)
    is_overdue = bool(due_date and due_date < timezone.localdate() and balance_due > 0)

    return {
        "id": invoice.id,
        "invoice_number": getattr(invoice, "invoice_number", ""),
        "purchase_order": getattr(invoice, "purchase_order_id", None),
        "purchase_order_number": getattr(purchase_order, "po_number", "") if purchase_order else "",
        "po_number": getattr(purchase_order, "po_number", "") if purchase_order else "",
        "supplier": getattr(invoice, "supplier_id", None),
        "supplier_name": getattr(supplier, "name", "") if supplier else "",
        "status": getattr(invoice, "status", ""),
        "subtotal_amount": money(subtotal_amount),
        "tax_amount": money(tax_amount),
        "total_amount": money(total_amount),
        "amount_paid": money(amount_paid),
        "balance_due": money(balance_due),
        "invoice_date": getattr(invoice, "invoice_date", None),
        "due_date": due_date,
        "is_overdue": is_overdue,
        "notes": getattr(invoice, "notes", ""),
        "created_at": getattr(invoice, "created_at", None),
        "payments": payments,
    }


def get_dashboard_payload():
    today = timezone.localdate()

    invoices = SupplierInvoice.objects.all()
    payments = SupplierPayment.objects.all()

    total_invoices = invoices.count()
    total_payables = invoices.aggregate(total=Sum("balance_due"))["total"] or Decimal("0.00")
    total_invoiced_amount = invoices.aggregate(total=Sum("total_amount"))["total"] or Decimal("0.00")
    total_input_tax = invoices.aggregate(total=Sum("tax_amount"))["total"] or Decimal("0.00")
    total_paid_amount = invoices.aggregate(total=Sum("amount_paid"))["total"] or Decimal("0.00")

    overdue_qs = invoices.filter(due_date__lt=today).exclude(status="paid")
    overdue_count = overdue_qs.count()
    overdue_amount = overdue_qs.aggregate(total=Sum("balance_due"))["total"] or Decimal("0.00")

    paid_today = payments.filter(payment_date=today).aggregate(total=Sum("amount"))["total"] or Decimal("0.00")
    payments_today_count = payments.filter(payment_date=today).count()

    recent_invoices = invoices.select_related("purchase_order", "supplier").order_by("-created_at")[:10]
    recent_payments = payments.select_related("invoice", "supplier").order_by("-payment_date", "-created_at")[:10]

    status_breakdown = {
        "unpaid": invoices.filter(status="unpaid").count(),
        "partial": invoices.filter(status="partial").count(),
        "paid": invoices.filter(status="paid").count(),
        "overdue": overdue_count,
    }

    supplier_balances = (
        invoices.values("supplier_id", "supplier__name")
        .annotate(
            invoice_count=Count("id"),
            total_invoiced=Sum("total_amount"),
            total_input_tax=Sum("tax_amount"),
            total_paid=Sum("amount_paid"),
            total_balance=Sum("balance_due"),
        )
        .order_by("-total_balance")[:10]
    )

    supplier_balances_data = [
        {
            "supplier_id": row["supplier_id"],
            "supplier_name": row["supplier__name"] or "",
            "invoice_count": row["invoice_count"] or 0,
            "total_invoiced": money(row["total_invoiced"] or Decimal("0.00")),
            "total_input_tax": money(row["total_input_tax"] or Decimal("0.00")),
            "total_paid": money(row["total_paid"] or Decimal("0.00")),
            "total_balance": money(row["total_balance"] or Decimal("0.00")),
        }
        for row in supplier_balances
    ]

    return {
        "summary": {
            "total_invoices": total_invoices,
            "total_invoiced_amount": money(total_invoiced_amount),
            "total_input_tax": money(total_input_tax),
            "total_paid_amount": money(total_paid_amount),
            "total_payables": money(total_payables),
            "overdue_count": overdue_count,
            "overdue_amount": money(overdue_amount),
            "paid_today": money(paid_today),
            "payments_today_count": payments_today_count,
        },
        "status_breakdown": status_breakdown,
        "recent_invoices": [serialize_invoice(invoice) for invoice in recent_invoices],
        "recent_payments": [serialize_payment(payment) for payment in recent_payments],
        "supplier_balances": supplier_balances_data,
    }


class SupplierInvoiceListView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        queryset = SupplierInvoice.objects.select_related(
            "purchase_order",
            "supplier",
        ).all().order_by("-created_at")

        supplier_id = request.GET.get("supplier")
        status_value = request.GET.get("status")
        overdue_only = request.GET.get("overdue")

        if supplier_id:
            queryset = queryset.filter(supplier_id=supplier_id)

        if status_value:
            queryset = queryset.filter(status=status_value)

        if str(overdue_only).lower() in ["1", "true", "yes"]:
            queryset = queryset.filter(due_date__lt=timezone.localdate()).exclude(status="paid")

        return Response([serialize_invoice(invoice) for invoice in queryset])


class SupplierPaymentListView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        queryset = SupplierPayment.objects.select_related(
            "invoice",
            "supplier",
        ).all().order_by("-payment_date", "-created_at")

        supplier_id = request.GET.get("supplier")
        invoice_id = request.GET.get("invoice")

        if supplier_id:
            queryset = queryset.filter(supplier_id=supplier_id)

        if invoice_id:
            queryset = queryset.filter(invoice_id=invoice_id)

        return Response([serialize_payment(payment) for payment in queryset])


class SupplierPaymentCreateView(APIView):
    permission_classes = [IsAuthenticated, IsFinance]

    def post(self, request):
        invoice_id = request.data.get("invoice_id") or request.data.get("invoice")
        amount = decimal_value(request.data.get("amount", 0))
        payment_method = request.data.get("payment_method", "bank_transfer")
        payment_date = request.data.get("payment_date") or timezone.localdate()
        reference = request.data.get("reference", "")
        notes = request.data.get("notes", "")

        if not invoice_id:
            return Response({"detail": "Invoice is required."}, status=status.HTTP_400_BAD_REQUEST)

        if amount <= 0:
            return Response({"detail": "Amount must be greater than zero."}, status=status.HTTP_400_BAD_REQUEST)

        invoice = get_object_or_404(SupplierInvoice, id=invoice_id)

        if amount > decimal_value(invoice.balance_due):
            return Response(
                {"detail": "Payment amount cannot exceed invoice balance."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        payment = SupplierPayment.objects.create(
            payment_number=f"PAY-{timezone.now().strftime('%Y%m%d%H%M%S%f')}",
            invoice=invoice,
            supplier=invoice.supplier,
            amount=amount,
            payment_method=payment_method,
            payment_date=payment_date,
            reference=reference,
            notes=notes,
            created_by=request.user if request.user.is_authenticated else None,
        )

        invoice.amount_paid = decimal_value(invoice.amount_paid) + amount
        invoice.balance_due = decimal_value(invoice.total_amount) - decimal_value(invoice.amount_paid)

        if invoice.amount_paid >= invoice.total_amount:
            invoice.status = "paid"
        elif invoice.amount_paid > 0:
            invoice.status = "partial"
        else:
            invoice.status = "unpaid"

        invoice.save(update_fields=["amount_paid", "balance_due", "status", "updated_at"])

        create_audit_log(
            actor=request.user,
            action="supplier_payment_created",
            target_type="supplier_payment",
            target_id=payment.id,
            description=f"Recorded payment {payment.payment_number} for invoice {invoice.invoice_number}.",
            metadata={
                "invoice_id": invoice.id,
                "invoice_number": invoice.invoice_number,
                "supplier_id": invoice.supplier_id,
                "supplier_name": getattr(invoice.supplier, "name", ""),
                "amount": str(amount),
                "payment_method": payment_method,
                "payment_date": str(payment_date),
                "reference": reference,
            },
        )

        return Response(
            {
                "detail": "Payment recorded successfully.",
                "payment": serialize_payment(payment),
                "invoice": serialize_invoice(invoice),
            },
            status=status.HTTP_201_CREATED,
        )


class FinanceDashboardView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        return Response(get_dashboard_payload())


class SupplierInvoicePdfView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, invoice_id):
        invoice = get_object_or_404(
            SupplierInvoice.objects.select_related("supplier", "purchase_order"),
            id=invoice_id,
        )

        po = getattr(invoice, "purchase_order", None)
        po_items = []
        if po and hasattr(po, "items"):
            po_items = po.items.select_related("product").all()

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)

        draw_header(pdf, "Supplier Invoice", f"Invoice No: {invoice.invoice_number}")

        y = 250 * mm
        pdf.setFont("Helvetica", 10)
        pdf.drawString(20 * mm, y, f"Supplier: {getattr(invoice.supplier, 'name', '')}")
        y -= 6 * mm
        pdf.drawString(20 * mm, y, f"PO Number: {getattr(po, 'po_number', '') if po else ''}")
        y -= 6 * mm
        pdf.drawString(20 * mm, y, f"Invoice Date: {invoice.invoice_date or invoice.created_at.date()}")
        y -= 6 * mm
        pdf.drawString(20 * mm, y, f"Due Date: {invoice.due_date or '-'}")
        y -= 6 * mm
        pdf.drawString(20 * mm, y, f"Status: {invoice.status}")
        y -= 10 * mm

        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(20 * mm, y, "Product")
        pdf.drawString(100 * mm, y, "Qty")
        pdf.drawString(125 * mm, y, "Unit Cost")
        pdf.drawString(160 * mm, y, "Line Total")
        y -= 4 * mm
        pdf.line(20 * mm, y, 190 * mm, y)
        y -= 6 * mm

        pdf.setFont("Helvetica", 10)
        for item in po_items:
            line_total = decimal_value(item.quantity) * decimal_value(item.unit_cost)
            pdf.drawString(20 * mm, y, getattr(item.product, "name", ""))
            pdf.drawString(100 * mm, y, str(item.quantity))
            pdf.drawString(125 * mm, y, f"£{money(item.unit_cost)}")
            pdf.drawString(160 * mm, y, f"£{money(line_total)}")
            y -= 7 * mm

            if y < 40 * mm:
                draw_footer(pdf)
                pdf.showPage()
                draw_header(pdf, "Supplier Invoice", f"Invoice No: {invoice.invoice_number}")
                y = 250 * mm

        y -= 4 * mm
        pdf.line(120 * mm, y, 190 * mm, y)
        y -= 8 * mm
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(120 * mm, y, f"Net: £{money(invoice.subtotal_amount)}")
        y -= 7 * mm
        pdf.drawString(120 * mm, y, f"Tax: £{money(invoice.tax_amount)}")
        y -= 7 * mm
        pdf.drawString(120 * mm, y, f"Total: £{money(invoice.total_amount)}")
        y -= 7 * mm
        pdf.drawString(120 * mm, y, f"Paid: £{money(invoice.amount_paid)}")
        y -= 7 * mm
        pdf.drawString(120 * mm, y, f"Balance: £{money(invoice.balance_due)}")

        draw_footer(pdf)
        pdf.save()

        buffer.seek(0)
        return FileResponse(
            buffer,
            as_attachment=True,
            filename=f"{invoice.invoice_number}.pdf",
            content_type="application/pdf",
        )


class FinanceExportInvoicesCsvView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        invoices = SupplierInvoice.objects.select_related("purchase_order", "supplier").all().order_by("-created_at")

        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="finance_invoices.csv"'

        writer = csv.writer(response)
        writer.writerow([
            "Invoice Number",
            "PO Number",
            "Supplier",
            "Status",
            "Invoice Date",
            "Due Date",
            "Subtotal Amount",
            "Tax Amount",
            "Total Amount",
            "Amount Paid",
            "Balance Due",
            "Created At",
        ])

        for invoice in invoices:
            po = getattr(invoice, "purchase_order", None)
            writer.writerow([
                getattr(invoice, "invoice_number", ""),
                getattr(po, "po_number", "") if po else "",
                getattr(invoice.supplier, "name", "") if getattr(invoice, "supplier", None) else "",
                getattr(invoice, "status", ""),
                getattr(invoice, "invoice_date", "") or "",
                getattr(invoice, "due_date", "") or "",
                money(getattr(invoice, "subtotal_amount", 0)),
                money(getattr(invoice, "tax_amount", 0)),
                money(getattr(invoice, "total_amount", 0)),
                money(getattr(invoice, "amount_paid", 0)),
                money(getattr(invoice, "balance_due", 0)),
                getattr(invoice, "created_at", "") or "",
            ])

        return response


class FinanceExportPaymentsCsvView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        payments = SupplierPayment.objects.select_related("invoice", "supplier").all().order_by("-payment_date", "-created_at")

        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="finance_payments.csv"'

        writer = csv.writer(response)
        writer.writerow([
            "Payment Number",
            "Reference",
            "Invoice Number",
            "Supplier",
            "Payment Method",
            "Payment Date",
            "Amount",
            "Notes",
            "Created At",
        ])

        for payment in payments:
            writer.writerow([
                getattr(payment, "payment_number", ""),
                getattr(payment, "reference", "") or "",
                getattr(payment.invoice, "invoice_number", "") if getattr(payment, "invoice", None) else "",
                getattr(payment.supplier, "name", "") if getattr(payment, "supplier", None) else "",
                getattr(payment, "payment_method", ""),
                getattr(payment, "payment_date", "") or "",
                money(getattr(payment, "amount", 0)),
                getattr(payment, "notes", "") or "",
                getattr(payment, "created_at", "") or "",
            ])

        return response


class FinanceExportSummaryCsvView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        data = get_dashboard_payload()
        summary = data["summary"]
        status_breakdown = data["status_breakdown"]

        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="finance_summary.csv"'

        writer = csv.writer(response)
        writer.writerow(["Metric", "Value"])
        writer.writerow(["Total Invoices", summary["total_invoices"]])
        writer.writerow(["Total Invoiced Amount", summary["total_invoiced_amount"]])
        writer.writerow(["Total Input Tax", summary["total_input_tax"]])
        writer.writerow(["Total Paid Amount", summary["total_paid_amount"]])
        writer.writerow(["Total Payables", summary["total_payables"]])
        writer.writerow(["Overdue Count", summary["overdue_count"]])
        writer.writerow(["Overdue Amount", summary["overdue_amount"]])
        writer.writerow(["Paid Today", summary["paid_today"]])
        writer.writerow(["Payments Today Count", summary["payments_today_count"]])
        writer.writerow(["Status Unpaid", status_breakdown["unpaid"]])
        writer.writerow(["Status Partial", status_breakdown["partial"]])
        writer.writerow(["Status Paid", status_breakdown["paid"]])
        writer.writerow(["Status Overdue", status_breakdown["overdue"]])

        return response