# Generated by Django 6.0.3 on 2026-03-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wh', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wh', to='inventory.warehouse'),
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
    ]
