# Generated by Django 5.2.12 on 2026-04-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=120, unique=True)),
                ('terminal_name', models.CharField(max_length=120)),
                ('preferred_print_mode', models.CharField(default='browser', max_length=30)),
                ('auto_print', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_last_seen_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['terminal_name', 'terminal_id'],
            },
        ),
    ]
