# Generated by Django 5.2.12 on 2026-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_anomalycase'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalycase',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalycase',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anomalycase',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
