# Generated by Django 5.2.12 on 2026-04-06 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_anomalycaseactivity_anomalycasetimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalycase',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalycase',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalycase',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalycase',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anomalycasetimeline',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority Changed'), ('note_updated', 'Note Updated'), ('resolution_updated', 'Resolution Updated'), ('evidence_added', 'Evidence Added'), ('sla_set', 'SLA Set'), ('sla_breached', 'SLA Breached'), ('escalated', 'Escalated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalycasetimeline',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_anomaly_case_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
