# Generated by Django 5.2.12 on 2026-04-07 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_anomalycase_escalated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('auto_case_created_count', models.PositiveIntegerField(default=0)),
                ('auto_case_reused_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_date', models.DateField(db_index=True)),
                ('anomaly_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='anomaly_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='auto_created',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='detected_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='escalation_level',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='severity',
            field=models.CharField(db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='sla_breached',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anomalycaseevidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='anomalycaseevidence',
            name='original_filename',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='anomalycasetimeline',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority Changed'), ('note_updated', 'Note Updated'), ('resolution_updated', 'Resolution Updated'), ('evidence_added', 'Evidence Added'), ('sla_set', 'SLA Set'), ('sla_breached', 'SLA Breached'), ('escalated', 'Escalated')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalycasetimeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['status', '-created_at'], name='accounts_an_status_c147af_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['priority', '-created_at'], name='accounts_an_priorit_f9694f_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['assigned_to', 'status'], name='accounts_an_assigne_154e13_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['sla_breached', 'status'], name='accounts_an_sla_bre_ac0f32_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['detected_date', 'anomaly_type'], name='accounts_an_detecte_a9fd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycase',
            index=models.Index(fields=['source_reference', 'detected_date'], name='accounts_an_source__b418d2_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycaseevidence',
            index=models.Index(fields=['case', '-created_at'], name='accounts_an_case_id_8be127_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycasetimeline',
            index=models.Index(fields=['case', '-created_at'], name='accounts_an_case_id_59ffc4_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalycasetimeline',
            index=models.Index(fields=['action', '-created_at'], name='accounts_an_action_5cdf54_idx'),
        ),
        migrations.AddField(
            model_name='storedanomaly',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_anomalies', to='accounts.anomalycase'),
        ),
        migrations.AddField(
            model_name='storedanomaly',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='accounts.anomalyscanrun'),
        ),
    ]
