# Generated by Django 5.2.12 on 2026-06-10 12:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('ecocash', 'EcoCash'), ('innbucks', 'InnBucks'), ('mukuru', 'Mukuru'), ('zipit', 'ZIPIT')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('internal_reference', models.CharField(max_length=120, unique=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
