# Generated by Django 5.2.12 on 2026-04-21 14:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stock_options_and_more'),
        ('sales', '0003_remove_sale_updated_at_sale_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='line_cost',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='line_profit',
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('ecocash', 'EcoCash'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='terminal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SaleItemBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.saleitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_allocations', to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='OfflineSaleSyncLog',
        ),
    ]
